Repository thoth-station/osiris-build-observer, pull requests merged in 2019-04, with the labels that each got.

#28 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#29 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#30 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#31 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#33 Add Thoth's configuration file
  .thoth.yml
Labels: approved, size/S

#32 Update README.md
  README.md
Labels: approved, size/M

#34 Automatic update of dependency openshift from 0.8.7 to 0.8.8
  Pipfile.lock
Labels: bot
